
#include "py/runtime.h"

#include "mods/pybrng.h"
#include "mods/pybuart.h"


// urandom(n)
// Return a bytes object with n random bytes, generated by
// the hardware random number generator.
static mp_obj_t mp_os_urandom(mp_obj_t num)
{
    mp_int_t n = mp_obj_get_int(num);
    vstr_t vstr;
    vstr_init_len(&vstr, n);
    for(int i = 0; i < n; i++)
    {
        vstr.buf[i] = rng_get();
    }
    return mp_obj_new_bytes_from_vstr(&vstr);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mp_os_urandom_obj, mp_os_urandom);


bool mp_os_dupterm_is_builtin_stream(mp_const_obj_t stream)
{
    const mp_obj_type_t *type = mp_obj_get_type(stream);

    return type == &pyb_uart_type
           #if MICROPY_HW_ENABLE_USB
           || type == &pyb_usb_vcp_type
           #endif
    ;
}
